language: ruby

sudo: required

matrix:
  include:
    - os: osx
      osx_image: xcode9.2
      rvm: system
    - os: linux
      rvm: 2.3

install:
  - unset DYLD_LIBRARY_PATH
  - if [ `uname` = "Linux" ]; then bash setup_travis_linux.sh; fi
  - if [ `uname` = "Linux" ]; then export PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"; fi
  - if [ `uname` = "Linux" ]; then brew install pkg-config; fi
  - brew tap homebrew/science
  # Install homebrew/cutest as tap.
  - mkdir -p $(brew --repo)/Library/Taps/optimizers
  - ln -s $PWD $(brew --repo)/Library/Taps/optimizers/homebrew-cutest
  - chmod 0644 $(brew --repo)/Library/Taps/optimizers/homebrew-cutest/*.rb
  - brew tap --repair
  - brew update
  - if [ `uname` == "Darwin" ]; then brew install svn; fi  # avoid annoyances with certificates

script:
  - brew test-bot --tap=optimizers/cutest
