language: ruby

sudo: required

matrix:
  include:
    - os: osx
      osx_image: xcode8.1
      rvm: system
    - os: linux
      rvm: 2.0.0

install:
  - unset DYLD_LIBRARY_PATH
  - if [ `uname` = "Linux" ]; then bash setup_travis_linux.sh; fi
  - if [ `uname` = "Linux" ]; then export PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"; fi
  - if [ `uname` = "Linux" ]; then brew install pkg-config; fi
  - brew tap homebrew/science
  # Install homebrew/cutest as tap.
  - mkdir -p $(brew --repo)/Library/Taps/optimizers
  - ln -s $PWD $(brew --repo)/Library/Taps/optimizers/homebrew-cutest
  - brew tap --repair
  - brew update

script:
  - brew test-bot --tap=optimizers/cutest
